in_file = in_file = open('C:/Users/rwmo2/Documents/Python Scripts/mydata2.txt', 'r+')
#print(in_file.read(1))
print(in_file.readline())
in_file.seek(0)
in_file.write('Hi!')
in_file.seek(0)
print(in_file.readline())
#print(in_file.tell())
in_file.close()
